# Generated by Django 4.2.6 on 2023-10-21 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_signin_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signin',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.signin'),
        ),
    ]
